openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: 'https://api.example.com/'
paths:
  /users:
    get:
      responses:
        "200":
          description: "A JSON array of usernames"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /users/create:
    post:
      responses:
        "200":
          description: "Successfully created user"
        "409":
          description: "User already exists"
        "400":
          description: "Malformed request body"
  /users/{userID}:
    get:
      responses:
        "200":
          description: "A summary of attributes for the target user."
          content:
            application/json:
              schema:
                type: object
        "404":
          description: "The target user was not found."