openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: 'https://api.example.com/'
paths:
  /users:
    get:
      responses:
        "200":
          description: "A JSON array of usernames"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /users/{userID}:
    get:
      responses:
        "200":
          description: "A summary of attributes for the target user."
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
        "404":
          description: "The target user was not found."